// Code generated by "stringer -type RankType"; DO NOT EDIT.

package stated

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Combat-0]
	_ = x[Trade-1]
	_ = x[Explore-2]
	_ = x[CQC-3]
	_ = x[Federation-4]
	_ = x[Empire-5]
	_ = x[RanksNum-6]
}

const _RankType_name = "CombatTradeExploreCQCFederationEmpireRanksNum"

var _RankType_index = [...]uint8{0, 6, 11, 18, 21, 31, 37, 45}

func (i RankType) String() string {
	if i < 0 || i >= RankType(len(_RankType_index)-1) {
		return "RankType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RankType_name[_RankType_index[i]:_RankType_index[i+1]]
}
