// Code generated by "stringer -type CoreSlot"; DO NOT EDIT.

package ships

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PowerPlant-0]
	_ = x[Thrusters-1]
	_ = x[FSD-2]
	_ = x[LifeSupport-3]
	_ = x[PowerDitsr-4]
	_ = x[Sensors-5]
	_ = x[FuelTank-6]
}

const _CoreSlot_name = "PowerPlantThrustersFSDLifeSupportPowerDitsrSensorsFuelTank"

var _CoreSlot_index = [...]uint8{0, 10, 19, 22, 33, 43, 50, 58}

func (i CoreSlot) String() string {
	if i < 0 || i >= CoreSlot(len(_CoreSlot_index)-1) {
		return "CoreSlot(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CoreSlot_name[_CoreSlot_index[i]:_CoreSlot_index[i+1]]
}
