// Code generated by "stringer -type Size"; DO NOT EDIT.

package ships

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SmallShip-1]
	_ = x[MediumShip-2]
	_ = x[LargeShip-3]
}

const _Size_name = "SmallShipMediumShipLargeShip"

var _Size_index = [...]uint8{0, 9, 19, 28}

func (i Size) String() string {
	i -= 1
	if i < 0 || i >= Size(len(_Size_index)-1) {
		return "Size(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Size_name[_Size_index[i]:_Size_index[i+1]]
}
