// Code generated by "stringer -type HardpointSize"; DO NOT EDIT.

package ship

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Utility-0]
	_ = x[SmallWeapon-1]
	_ = x[MediumWeapon-2]
	_ = x[LargeWeapon-3]
	_ = x[HugeWeapon-4]
}

const _HardpointSize_name = "UtilitySmallWeaponMediumWeaponLargeWeaponHugeWeapon"

var _HardpointSize_index = [...]uint8{0, 7, 18, 30, 41, 51}

func (i HardpointSize) String() string {
	if i < 0 || i >= HardpointSize(len(_HardpointSize_index)-1) {
		return "HardpointSize(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HardpointSize_name[_HardpointSize_index[i]:_HardpointSize_index[i+1]]
}
