// Code generated by "stringer -type OptSlotRestriction"; DO NOT EDIT.

package ship

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OptAll-0]
	_ = x[OptMilitary-1]
}

const _OptSlotRestriction_name = "OptAllOptMilitary"

var _OptSlotRestriction_index = [...]uint8{0, 6, 17}

func (i OptSlotRestriction) String() string {
	if i < 0 || i >= OptSlotRestriction(len(_OptSlotRestriction_index)-1) {
		return "OptSlotRestriction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OptSlotRestriction_name[_OptSlotRestriction_index[i]:_OptSlotRestriction_index[i+1]]
}
